# Generated by Django 2.0 on 2019-03-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='head',
            field=models.CharField(max_length=60),
        ),
    ]
