# Generated by Django 2.0 on 2019-03-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0002_auto_20190316_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='body',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='head',
            field=models.CharField(max_length=100),
        ),
    ]
