# Generated by Django 2.0 on 2019-03-26 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0003_auto_20190326_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdata',
            name='image',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
