# Generated by Django 2.1.7 on 2019-03-29 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0004_newsdata_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsdata',
            name='image',
        ),
    ]
