# Generated by Django 2.1.7 on 2019-04-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0005_remove_newsdata_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
