# Generated by Django 2.1.7 on 2019-04-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0007_auto_20190411_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdata',
            name='category',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
