# Generated by Django 2.1.7 on 2019-04-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0008_newsdata_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='category',
            field=models.CharField(max_length=10),
        ),
    ]
