# Generated by Django 2.1.7 on 2019-04-10 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0009_auto_20190411_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsdata',
            name='category',
        ),
    ]
